Capsule/mask classifier
aotuai/capsule-zoo pull request #11
Opened 2020-12-03 01:43 UTC by apockill

2020-12-03 18:06 UTC, velovix approved these changes

2020-12-03 18:06 UTC, velovix commented on capsules/segmenter_person_openvino/licenses/model.license
> +                                 Apache License
Duplicate license file

2020-12-03 18:06 UTC, velovix commented on capsules/segmenter_person_openvino/capsule.py
> +from vcap import (
Probably segmenter_person_openvino is not supposed to be in this PR.

2020-12-03 21:49 UTC, BryceBeagle requested changes
This PR includes changes from other capsules. Was this intentional?

2020-12-03 21:49 UTC, BryceBeagle commented on capsules/classifier_mask_closeup/meta.conf
> +api_compatibility_version = 0.2
newline

2020-12-04 19:07 UTC, apockill commented on capsules/classifier_mask_closeup/meta.conf
> +api_compatibility_version = 0.2
Fixed

2020-12-04 19:08 UTC, apockill commented
@BryceBeagle initially I didn't mean to add them, but then I realized I'd committed some improvements that I'd intended to push anyways, and so I fit them in this review. 

It basically fixed a bug with the vehicle classifier where the label "vehicle" was supposed to be "car", according to the model. All the truck/bus predictions were incorrect because of this bug.

2020-12-04 19:13 UTC, BryceBeagle commented
I'd suggest checking the PR name, then

2020-12-05 01:44 UTC, merged