Added classifier_face_emotion_openvino
aotuai/capsule-zoo pull request #5
Opened 2020-10-02 20:14 UTC by rhedgeco

2020-10-02 20:44 UTC, apockill commented on capsules/classifier_face_emotion_openvino/config.py
> +emotion_types = ['neutral', 'happy', 'sad', 'surprise', 'anger']
Tbh having a config for one line probably isn't necessary :P You can have it in the backend and import it from capsule.py to do the same thing

2020-10-02 21:05 UTC, BryceBeagle requested changes

2020-10-02 21:05 UTC, BryceBeagle commented on capsules/classifier_face_emotion_openvino/README.md
> +This capsule is for detecting the the emotion of faces in video. It should be
the the

2020-10-02 21:05 UTC, BryceBeagle commented on capsules/classifier_face_emotion_openvino/meta.conf
> +api_compatibility_version = 0.2
Nitpick: new line at end of file

2020-10-02 21:08 UTC, BryceBeagle commented on capsules/classifier_face_emotion_openvino/meta.conf
> +api_compatibility_version = 0.2
For reference: https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

2020-10-02 21:37 UTC, BryceBeagle approved these changes

2020-10-02 22:48 UTC, velovix approved these changes

2020-10-06 20:29 UTC, apockill approved these changes

2020-10-06 20:30 UTC, apockill commented
This is ready for merging. @rhedgeco feel free to merge at your leisure, unless you anticipate further changes.

2020-10-06 20:58 UTC, rhedgeco commented
lol gimme that shirt

2020-10-06 20:58 UTC, merged